language: python
sudo: yes

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-ansible21
    - python: 2.7
      env: TOXENV=py27-ansible20
    - python: 2.7
      env: TOXENV=py27-ansible19

install:
  - pip install tox

script:
  - tox

notifications:
  email: false
  slack:
    template:
      - "%{repository_name}@%{branch} %{commit} : [%{build_number}] %{result} "
      - "%{build_url}"
      - "'%{commit_subject}' by %{author}"
      - "%{elapsed_time} : %{duration}"
      - "%{message}"
    rooms:
      secure: "ObF02eNHULzrJgnm4z561zhjmYJf5pQPsGscTtpVTCsf0p/wb3cLwPae6ZD6SSAlguv0j8VuaA1RsZJLOBdgBRuQYa0e1QNkdDc8UDW0bH3CgjHmtpXcVT9JZKBAWB9TJqxj4gSFkUleAsl8UyhDKloRhniQgqNszNwCccZc2sc="
    on_success: always
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log

cache:
  directories:
    - "${HOME}/.cache/pip"
