language: python
sudo: yes

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-ansible21
    - python: 2.7
      env: TOXENV=py27-ansible20
    - python: 2.7
      env: TOXENV=py27-ansible19

install:
  - pip install tox

script:
  - tox

notifications:
  email: false
  slack:
    template:
      - "%{repository_name}@%{branch} %{commit} : [%{build_number}] %{result} "
      - "%{build_url}"
      - "'%{commit_subject}' by %{author}"
      - "%{elapsed_time} : %{duration}"
      - "%{message}"
    rooms:
      secure: NseuBf+nDfigQrfcpOyyQor4928/D4i8zWK8OnJAWYxNYHKcmojbZcL+uAfDeJm2YkQGba1A92XZTEBx/nVUluHNVnexJP7309Rp0ql1h/kO1AC4iO1gZseUdAA3R8uDMXSuOWRhBgP8udb5Ys/qlN/feyjtvn4rTA0L1EKIPPc=
    on_success: always
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log

cache:
  directories:
    - "${HOME}/.cache/pip"
